[workspace]
channels = ["conda-forge"]
name = "summer2pixi"
platforms = ["osx-arm64", "win-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
ipykernel = ">=7.2.0,<8"
ipywidgets = ">=8.1.8,<9"

[pypi-dependencies]
summerepi2 = ">=1.3.6, <2"
estival = ">=0.5.2, <0.6"
numpyro = ">=0.19.0, <0.20"
pymc = ">=5.25.1, <6"
